# Generated by Django 3.1 on 2025-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('CREATE_USER', 'CREATE_USER'), ('DELETE_USER', 'DELETE_USER'), ('OTHER_ADMIN_DELETED', 'OTHER_ADMIN_DELETED'), ('DELETE_SUBSCRIPTION', 'DELETE_SUBSCRIPTION'), ('SUBSCRIPTION_TRIALS_WILL_END', 'SUBSCRIPTION_TRIALS_WILL_END'), ('RIGHTS_UPDATED', 'RIGHTS_UPDATED')], max_length=32, verbose_name="Type d'email")),
                ('langue', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2, verbose_name='Langue')),
                ('template_id', models.IntegerField(verbose_name='ID du template')),
                ('sujet', models.CharField(max_length=128, verbose_name='Sujet')),
            ],
        ),
    ]
