# Generated by Django 3.1 on 2025-06-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailsettings',
            unique_together={('email_type', 'langue')},
        ),
    ]
