# Generated by Django 3.1 on 2025-06-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20250604_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsettings',
            old_name='sujet',
            new_name='subject',
        ),
    ]
