# Generated by Django 3.1 on 2025-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20250605_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_type',
            field=models.CharField(choices=[('USER_CREATED', 'USER_CREATED'), ('USER_DELETED', 'USER_DELETED'), ('USER_DELETED_WARN_ADMIN', 'USER_DELETED_WARN_ADMIN'), ('SUBSCRIPTION_UPDATED_QUANTITY', 'SUBSCRIPTION_UPDATED_QUANTITY'), ('SUBSCRIPTION_UPDATED_INACTIVE', 'SUBSCRIPTION_UPDATED_INACTIVE'), ('SUBSCRIPTION_NEED_PAYMENT', 'SUBSCRIPTION_NEED_PAYMENT'), ('SUBSCRIPTION_DELETED', 'SUBSCRIPTION_DELETED'), ('SUBSCRIPTION_TRIALS_WILL_END', 'SUBSCRIPTION_TRIALS_WILL_END')], max_length=64, verbose_name="Type d'email"),
        ),
    ]
