# Generated by Django 3.1 on 2025-01-XX XX:XX

from django.db import migrations


def populate_email_settings(apps, schema_editor):
    EmailSettings = apps.get_model('emails', 'EmailSettings')
    EmailSettings.objects.all().delete()

    email_settings_data = [
        # French emails
        ('SUBSCRIPTION_DELETED', 'fr', 211810,
         'Lexamt.fr - Suppression de votre abonnement'),
        ('SUBSCRIPTION_NEED_PAYMENT', 'fr', 211809,
         'Lexamt.fr - Défaut de paiement détécté'),
        ('SUBSCRIPTION_TRIALS_WILL_END', 'fr', 211811,
         'Lexamt.fr - Votre période d\'essai arrive à expiration'),
        ('SUBSCRIPTION_UPDATED_INACTIVE', 'fr', 211808,
         'Lexamt.fr - Votre abonnement  est devenu inactif'),
        ('SUBSCRIPTION_UPDATED_QUANTITY', 'fr', 211807,
         'Lexamt.fr - Modification de votre abonnement confirmé'),
        ('USER_CREATED', 'fr', 211686, 'Lexamt.fr - Bienvenue et accès à votre compte'),
        ('USER_DELETED', 'fr', 211802, 'Lexamt.fr - Votre compte a été supprimé'),
        ('USER_DELETED_WARN_ADMIN', 'fr', 211806,
         'Lexamt.fr - Confirmation de la suppression  de votre compte'),

        # English emails
        ('SUBSCRIPTION_DELETED', 'en', 211923,
         'Lexamt.com - Your subscription has been cancelled'),
        ('SUBSCRIPTION_NEED_PAYMENT', 'en', 211924,
         'Lexamt.com - Payment failure detected'),
        ('SUBSCRIPTION_TRIALS_WILL_END', 'en', 211925,
         'Lexamt.com - Your trial period is expiring'),
        ('SUBSCRIPTION_UPDATED_INACTIVE', 'en', 211926,
         'Lexamt.com - Your subscription has become inactive'),
        ('SUBSCRIPTION_UPDATED_QUANTITY', 'en', 211951,
         'Lexamt.com - Subscription modification confirmed'),
        ('USER_CREATED', 'en', 211927,
         'Lexamt.com - Welcome and access to your account'),
        ('USER_DELETED', 'en', 211946, 'Lexamt.com - Your account has been deleted'),
        ('USER_DELETED_WARN_ADMIN', 'en', 211948,
         'Lexamt.com - Account deletion confirmation'),
    ]

    for email_type, langue, template_id, subject in email_settings_data:
        EmailSettings.objects.get_or_create(
            email_type=email_type,
            langue=langue,
            defaults={
                'template_id': template_id,
                'subject': subject,
            }
        )


def reverse_populate_email_settings(apps, schema_editor):
    EmailSettings = apps.get_model('emails', 'EmailSettings')
    EmailSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20250605_1755'),
    ]

    operations = [
        migrations.RunPython(
            populate_email_settings,
            reverse_populate_email_settings,
        ),
    ]
