# Generated by Django 3.1 on 2025-06-26 08:52

from django.db import migrations, models


def clean_duplicates_after_rename(apps, schema_editor):
    # Clean duplicates after field rename
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DELETE FROM emails_emailsettings 
            WHERE id NOT IN (
                SELECT MIN(id) 
                FROM emails_emailsettings 
                GROUP BY email_type, language
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_populate_email_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsettings',
            old_name='langue',
            new_name='language',
        ),
        migrations.RunPython(
            clean_duplicates_after_rename,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='emailsettings',
            unique_together={('email_type', 'language')},
        ),
    ]
