# Generated by Django 3.1 on 2025-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_auto_20250626_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2, verbose_name='Language'),
        ),
    ]
