# Generated by Django 3.1 on 2025-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_auto_20250626_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_type',
            field=models.CharField(choices=[('USER_CREATED', 'USER_CREATED'), ('SUBSCRIPTION_UPDATED_QUANTITY_ADMIN', 'SUBSCRIPTION_UPDATED_QUANTITY_ADMIN'), ('SUBSCRIPTION_UPDATED_INACTIVE_ADMIN', 'SUBSCRIPTION_UPDATED_INACTIVE_ADMIN'), ('SUBSCRIPTION_UPDATED_INACTIVE', 'SUBSCRIPTION_UPDATED_INACTIVE'), ('SUBSCRIPTION_NEED_PAYMENT_ADMIN', 'SUBSCRIPTION_NEED_PAYMENT_ADMIN'), ('SUBSCRIPTION_DELETED_ADMIN', 'SUBSCRIPTION_DELETED_ADMIN'), ('SUBSCRIPTION_DELETED', 'SUBSCRIPTION_DELETED'), ('SUBSCRIPTION_TRIALS_WILL_END_ADMIN', 'SUBSCRIPTION_TRIALS_WILL_END_ADMIN'), ('SUBSCRIPTION_TRIALS_WILL_END', 'SUBSCRIPTION_TRIALS_WILL_END')], max_length=64, verbose_name="Type d'email"),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=8, verbose_name='Language'),
        ),
    ]
