# Generated by Django 3.1 on 2025-07-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_update_email_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'ordering': ['email_type', 'language'], 'verbose_name': 'Email Setting', 'verbose_name_plural': 'Email Settings'},
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_type',
            field=models.CharField(choices=[('USER_CREATED', 'USER_CREATED'), ('SUBSCRIPTION_UPDATED_QUANTITY_ADMIN', 'SUBSCRIPTION_UPDATED_QUANTITY_ADMIN'), ('SUBSCRIPTION_UPDATED_INACTIVE_ADMIN', 'SUBSCRIPTION_UPDATED_INACTIVE_ADMIN'), ('SUBSCRIPTION_UPDATED_INACTIVE', 'SUBSCRIPTION_UPDATED_INACTIVE'), ('SUBSCRIPTION_NEED_PAYMENT_ADMIN', 'SUBSCRIPTION_NEED_PAYMENT_ADMIN'), ('SUBSCRIPTION_DELETED_ADMIN', 'SUBSCRIPTION_DELETED_ADMIN'), ('SUBSCRIPTION_DELETED', 'SUBSCRIPTION_DELETED'), ('SUBSCRIPTION_TRIALS_WILL_END_ADMIN', 'SUBSCRIPTION_TRIALS_WILL_END_ADMIN'), ('SUBSCRIPTION_TRIALS_WILL_END', 'SUBSCRIPTION_TRIALS_WILL_END')], help_text='The type of email this setting applies to', max_length=64, verbose_name="Type d'email"),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], help_text='Language code for this email template', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='subject',
            field=models.CharField(help_text='Email subject line', max_length=128, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='template_id',
            field=models.IntegerField(help_text='Active Trail template identifier', verbose_name='ID du template'),
        ),
        migrations.AddIndex(
            model_name='emailsettings',
            index=models.Index(fields=['email_type', 'language'], name='emails_emai_email_t_5fae53_idx'),
        ),
    ]
