# Generated by Django 3.1 on 2025-12-16 16:00

from django.db import migrations, models


def create_user_adm_valide_quote_settings(apps, schema_editor):
    EmailSettings = apps.get_model('emails', 'EmailSettings')
    entries = [
        {
            'email_type': 'USER_ADM_VALIDE_QUOTE',
            'language': 'fr',
            'template_id': 216099,
            'subject': 'Lexamt.fr : Un utilisateur a validé son devis'
        },
        {
            'email_type': 'USER_ADM_VALIDE_QUOTE',
            'language': 'en',
            'template_id': 216099,
            'subject': 'Lexamt.com : A user validated his quote'
        },
    ]

    for entry in entries:
        EmailSettings.objects.update_or_create(
            email_type=entry['email_type'],
            language=entry['language'],
            defaults={
                'template_id': entry['template_id'],
                'subject': entry['subject'],
            }
        )


def delete_user_adm_valide_quote_settings(apps, schema_editor):
    EmailSettings = apps.get_model('emails', 'EmailSettings')
    EmailSettings.objects.filter(
        email_type='USER_ADM_VALIDE_QUOTE'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_auto_20251119_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_type',
            field=models.CharField(
                choices=[
                    ('USER_CREATED', 'USER_CREATED'),
                    ('ADDIN_CREATED', 'ADDIN_CREATED'),
                    ('SUBSCRIPTION_UPDATED_QUANTITY_ADMIN', 'SUBSCRIPTION_UPDATED_QUANTITY_ADMIN'),
                    ('SUBSCRIPTION_UPDATED_INACTIVE_ADMIN', 'SUBSCRIPTION_UPDATED_INACTIVE_ADMIN'),
                    ('SUBSCRIPTION_UPDATED_INACTIVE', 'SUBSCRIPTION_UPDATED_INACTIVE'),
                    ('SUBSCRIPTION_NEED_PAYMENT_ADMIN', 'SUBSCRIPTION_NEED_PAYMENT_ADMIN'),
                    ('SUBSCRIPTION_DELETED_ADMIN', 'SUBSCRIPTION_DELETED_ADMIN'),
                    ('SUBSCRIPTION_DELETED', 'SUBSCRIPTION_DELETED'),
                    ('SUBSCRIPTION_TRIALS_WILL_END_ADMIN', 'SUBSCRIPTION_TRIALS_WILL_END_ADMIN'),
                    ('SUBSCRIPTION_TRIALS_WILL_END', 'SUBSCRIPTION_TRIALS_WILL_END'),
                    ('USER_MANAGEMENT_INVITATION', 'USER_MANAGEMENT_INVITATION'),
                    ('USER_MANAGEMENT_QUOTE', 'USER_MANAGEMENT_QUOTE'),
                    ('USER_MANAGEMENT_RESET_PASSWORD', 'USER_MANAGEMENT_RESET_PASSWORD'),
                    ('USER_ADM_TR_FILE', 'USER_ADM_TR_FILE'),
                    ('USER_ADM_VALIDE_QUOTE', 'USER_ADM_VALIDE_QUOTE'),
                ],
                help_text='The type of email this setting applies to',
                max_length=64,
                verbose_name="Type d'email"
            ),
        ),
        migrations.RunPython(
            create_user_adm_valide_quote_settings,
            delete_user_adm_valide_quote_settings,
        ),
    ]

