# Generated by Django 3.1 on 2025-12-19

from django.db import migrations, models


def create_api_created_settings(apps, schema_editor):
    EmailSettings = apps.get_model('emails', 'EmailSettings')
    entries = [
        {
            'email_type': 'API_CREATED',
            'language': 'fr',
            'template_id': 216165,
            'subject': "Lexamt.fr : Bienvenue et accès à l'API Lexa"
        },
        {
            'email_type': 'API_CREATED',
            'language': 'en',
            'template_id': 216166,
            'subject': "Lexamt.com : Welcome and access to the Lexa API"
        },
    ]

    for entry in entries:
        EmailSettings.objects.update_or_create(
            email_type=entry['email_type'],
            language=entry['language'],
            defaults={
                'template_id': entry['template_id'],
                'subject': entry['subject'],
            }
        )


def delete_api_created_settings(apps, schema_editor):
    EmailSettings = apps.get_model('emails', 'EmailSettings')
    EmailSettings.objects.filter(
        email_type='API_CREATED'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_add_user_adm_valide_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_type',
            field=models.CharField(
                choices=[
                    ('USER_CREATED', 'USER_CREATED'),
                    ('ADDIN_CREATED', 'ADDIN_CREATED'),
                    ('API_CREATED', 'API_CREATED'),
                    ('SUBSCRIPTION_UPDATED_QUANTITY_ADMIN', 'SUBSCRIPTION_UPDATED_QUANTITY_ADMIN'),
                    ('SUBSCRIPTION_UPDATED_INACTIVE_ADMIN', 'SUBSCRIPTION_UPDATED_INACTIVE_ADMIN'),
                    ('SUBSCRIPTION_UPDATED_INACTIVE', 'SUBSCRIPTION_UPDATED_INACTIVE'),
                    ('SUBSCRIPTION_NEED_PAYMENT_ADMIN', 'SUBSCRIPTION_NEED_PAYMENT_ADMIN'),
                    ('SUBSCRIPTION_DELETED_ADMIN', 'SUBSCRIPTION_DELETED_ADMIN'),
                    ('SUBSCRIPTION_DELETED', 'SUBSCRIPTION_DELETED'),
                    ('SUBSCRIPTION_TRIALS_WILL_END_ADMIN', 'SUBSCRIPTION_TRIALS_WILL_END_ADMIN'),
                    ('SUBSCRIPTION_TRIALS_WILL_END', 'SUBSCRIPTION_TRIALS_WILL_END'),
                    ('USER_MANAGEMENT_INVITATION', 'USER_MANAGEMENT_INVITATION'),
                    ('USER_MANAGEMENT_QUOTE', 'USER_MANAGEMENT_QUOTE'),
                    ('USER_MANAGEMENT_RESET_PASSWORD', 'USER_MANAGEMENT_RESET_PASSWORD'),
                    ('USER_ADM_TR_FILE', 'USER_ADM_TR_FILE'),
                    ('USER_ADM_VALIDE_QUOTE', 'USER_ADM_VALIDE_QUOTE'),
                ],
                help_text='The type of email this setting applies to',
                max_length=64,
                verbose_name="Type d'email"
            ),
        ),
        migrations.RunPython(
            create_api_created_settings,
            delete_api_created_settings,
        ),
    ]
