# Generated by Django 3.1 on 2024-03-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='french_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name in French'),
        ),
    ]
