# Generated by Django 3.1 on 2024-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_french_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Abbreviation'),
        ),
    ]
