# Generated by Django 3.1 on 2024-12-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20240927_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Abbreviation'),
        ),
    ]
