# Generated by Django 3.1 on 2024-12-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0002_usergroup_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptiontype'),
        ),
    ]
