# Generated by Django 3.1 on 2024-12-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usergroup_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='subscription',
        ),
    ]
