# Generated by Django 3.1 on 2024-12-30 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usergroup_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='quote_monthly_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
