# Generated by Django 3.1 on 2025-01-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_resetpasswordcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPasswordCode',
        ),
    ]
