# Generated by Django 3.1 on 2025-04-03 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_resetpasswordcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='admin',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='admin',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
