# Generated by Django 3.1 on 2025-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20250403_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Stripe User ID'),
        ),
    ]
