# Generated by Django 3.1 on 2025-05-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Stripe customer ID'),
        ),
    ]
