# Generated by Django 3.1 on 2025-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20250526_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=32, verbose_name='Language'),
        ),
    ]
