# Generated by Django 3.1 on 2025-10-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_make_api_key_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='api_key',
        ),
    ]
