# Generated by Django 3.2.25 on 2026-01-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_api_key_from_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retention_period',
            field=models.IntegerField(choices=[(1, '1 jour'), (7, '7 jours'), (30, '30 jours'), (365, '1 an'), (730, '2 ans'), (1095, '3 ans'), (1825, '5 ans')], default=365, help_text='Nombre de jours avant suppression automatique des traductions', verbose_name='Période de rétention'),
        ),
    ]
