# Generated by Django 3.2.25 on 2026-01-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_retention_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_instructions',
            field=models.CharField(blank=True, help_text="Instructions personnalisées de traduction sauvegardées par l'utilisateur", max_length=2000, null=True, verbose_name='Instructions sauvegardées'),
        ),
    ]
