services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/django/dev.Dockerfile
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./
        target: /home/django/app/
    environment:
      - POSTGRES_USER=legal
      - DJANGO_PG_PASSWOR=datasvitend
      - DJANGO_PG_HOST=postgres
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=legal.settings_dev
      - DOCKER=true
    env_file:
      - .env
    networks:
      - lexamt-network

  dockerize:
    image: jwilder/dockerize
    platform: linux/amd64
    command: dockerize -wait tcp://postgres:5432 -timeout 10s
    depends_on:
      - postgres
    networks:
      - lexamt-network

  celery:
    <<: *django
    command: celery -A legal worker -l info
    environment:
      - POSTGRES_USER=legal
      - DJANGO_PG_PASSWOR=datasvitend
      - CELERY_REDIS=redis://redis:6379
    depends_on:
      - dockerize
      - redis
    restart: unless-stopped
    networks:
      - lexamt-network

  celery_beat:
    <<: *django
    command: celery -A legal beat -l info
    environment:
      - POSTGRES_USER=legal
      - DJANGO_PG_PASSWOR=datasvitend
      - CELERY_REDIS=redis://redis:6379
    depends_on:
      - dockerize
      - redis
    restart: unless-stopped
    networks:
      - lexamt-network

  runserver:
    <<: *django
    command: [ "bash", "./docker/django/start-dev.sh" ]
    ports:
      - 8099:8099
    depends_on:
      - dockerize
      - celery
      - redis
    restart: unless-stopped
    networks:
      - lexamt-network

  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=legal
      - DJANGO_PG_PASSWOR=datasvitend
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - lexamt-network

  redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - lexamt-network

networks:
  lexamt-network:
    external: true

volumes:
  postgres_data: