# Generated by Django 3.1 on 2025-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
