# Generated by Django 3.1 on 2025-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_webhooks', '0002_stripeevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeevent',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
