# Generated by Django 3.1 on 2025-06-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_webhooks', '0003_auto_20250515_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='code_reponse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='http_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
