# Generated by Django 3.1 on 2025-06-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_webhooks', '0004_auto_20250604_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeevent',
            old_name='code_reponse',
            new_name='code_response',
        ),
    ]
