# Generated by Django 3.1 on 2025-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_webhooks', '0005_auto_20250604_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripeevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stripe Event', 'verbose_name_plural': 'Stripe Events'},
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='code_response',
            field=models.IntegerField(blank=True, help_text='HTTP response code returned after processing', null=True),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='created_at',
            field=models.DateTimeField(help_text='Timestamp when the event was received'),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='data',
            field=models.JSONField(help_text='Raw event data from Stripe webhook payload'),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='event_id',
            field=models.CharField(help_text='Unique identifier for the Stripe event', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='event_type',
            field=models.CharField(help_text='Type of Stripe event (e.g., customer.created, invoice.paid)', max_length=255),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='http_response',
            field=models.JSONField(blank=True, help_text='Complete HTTP response data after processing', null=True),
        ),
        migrations.AlterField(
            model_name='stripeevent',
            name='status',
            field=models.CharField(blank=True, help_text='Processing status of the webhook event', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['event_type'], name='stripe_webh_event_t_0cd8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['created_at'], name='stripe_webh_created_ce33ba_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['status'], name='stripe_webh_status_b7e0d2_idx'),
        ),
    ]
