# Generated by Django 3.1 on 2024-12-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0004_auto_20241216_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_language_quotes_as_source', to='languages.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_language_quotes_as_target', to='languages.language')),
            ],
        ),
    ]
