# Generated by Django 3.1 on 2025-01-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagequote',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='€/word', max_digits=5),
        ),
    ]
