# Generated by Django 3.1 on 2025-01-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0002_auto_20250116_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagequote',
            options={'ordering': ['price']},
        ),
    ]
