# Generated by Django 3.1 on 2025-02-10 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('quoting', '0003_auto_20250122_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteConfig',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('daily_performance', models.IntegerField(default=100, help_text='words')),
                ('additional_time_for_order_processing', models.IntegerField(default=7, help_text='days')),
            ],
            options={
                'verbose_name': 'Quote Config',
                'verbose_name_plural': 'Quote Config',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
