# Generated by Django 3.1 on 2025-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0004_quoteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagequote',
            name='additional_time_for_order_processing',
            field=models.IntegerField(default=7, help_text='days'),
        ),
        migrations.AddField(
            model_name='languagequote',
            name='daily_performance',
            field=models.IntegerField(default=100, help_text='words'),
        ),
        migrations.DeleteModel(
            name='QuoteConfig',
        ),
    ]
