# Generated by Django 3.1 on 2024-09-12 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticSettings',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('API_KEY', models.CharField(max_length=255)),
                ('URL', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Statistic Settings',
                'verbose_name_plural': 'Statistic Settings',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
