# Generated by Django 3.1 on 2024-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='StatisticSettings',
            name='URL',
            field=models.URLField(default='https://statistic.portal.custom.mt/', max_length=255),
        ),
    ]
