# Generated by Django 3.1 on 2025-10-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20240923_1741'),
    ]

    operations = [
    ]
