# Generated by Django 3.1 on 2025-10-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_statistic_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticSettings',
        ),
    ]
