# Generated by Django 3.1 on 2024-10-01 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('variables', models.JSONField(default=dict)),
                ('temperature', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('gpt_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'en'), ('fr', 'fr')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='writing.prompt')),
            ],
        ),
    ]
