# Generated by Django 3.1 on 2025-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttranslation',
            name='icon',
            field=models.CharField(blank=True, help_text='Phosphor icon name (https://phosphoricons.com/)', max_length=100, null=True, verbose_name='icon'),
        ),
    ]
