# Generated by Django 3.1 on 2025-12-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_set_icons_from_fr_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompttranslation',
            name='prompt',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='PromptTranslation',
        ),
    ]
