# Generated by Django 3.1 on 2024-09-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='is_default_glossary',
            field=models.BooleanField(default=False),
        ),
    ]
