# Generated by Django 3.1 on 2024-09-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_french_name'),
        ('glossaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={'verbose_name': 'Glossary', 'verbose_name_plural': 'Glossaries'},
        ),
        migrations.AddField(
            model_name='glossary',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossaries.glossary'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='source_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_language_glossaries', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_language_glossaries', to='languages.language'),
        ),
    ]
