# Generated by Django 3.1 on 2024-09-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergroup_admin'),
        ('glossaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossary',
            name='is_default_glossary',
        ),
        migrations.AddField(
            model_name='glossary',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usergroup'),
        ),
    ]
