# Generated by Django 3.1 on 2024-09-19 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='file',
            field=models.FileField(upload_to='glossaries/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
