# Generated by Django 3.1 on 2024-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0002_auto_20240923_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
