# Generated by Django 3.1 on 2024-09-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        ('glossaries', '0003_auto_20240924_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossaries', to='domains.domain'),
        ),
    ]
