# Generated by Django 3.1 on 2025-04-07 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0004_auto_20240930_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='file',
            field=models.FileField(upload_to='glossaries/', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx'])]),
        ),
    ]
