# Generated by Django 3.1 on 2025-06-30 13:27
from django.core.exceptions import ValidationError
from django.db import migrations, models

from glossaries.services import AIGlossaryService


def fill_glossary_ids(apps, schema_editor):
    Glossary = apps.get_model('glossaries', 'Glossary')
    glossaries = Glossary.objects.all()

    for glossary in glossaries:
        #i = 0
        try:
            glossary.glossary_id = AIGlossaryService().create_glossary(glossary)
            #glossary.glossary_id = i
            glossary.save()
            #i += 1
        except ValidationError:
            glossary.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('glossaries', '0005_auto_20250407_1231'),
        #('settings', '0008_mainsettings_glossaries_url')
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='glossary_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(fill_glossary_ids),
    ]
