# Generated by Django 3.1 on 2025-08-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20241216_1707'),
        ('glossaries', '0006_glossary_glossary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_language_glossaries', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language_glossaries', to='languages.language'),
        ),
    ]
