# Generated by Django 3.2.25 on 2025-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0007_auto_20250819_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
