# Generated by Django 3.1 on 2026-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0008_auto_20251024_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated on each save to track last modification'),
        ),
    ]
