# Generated by Django 3.1 on 2024-01-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsettings',
            options={'verbose_name': 'Main Settings', 'verbose_name_plural': 'Main Settings'},
        ),
    ]
