# Generated by Django 3.1 on 2024-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20240123_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='algorithm',
            field=models.CharField(choices=[('template', 'Template'), ('domain', 'Domain')], default='template', max_length=32),
        ),
    ]
