# Generated by Django 3.1 on 2024-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_mainsettings_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='CLOUDSTORAGE_API_URL',
            field=models.URLField(default='https://s3.fileprocessing.custom.mt/translate/legal230/', max_length=256),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='CUSTOM_MT_CONSOLE_URL',
            field=models.URLField(default='https://console.custom.mt/translation/', max_length=256),
        ),
    ]
