# Generated by Django 3.1 on 2024-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20240723_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
