# Generated by Django 3.1 on 2024-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_mainsettings_support_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='CUSTOM_MT_CONSOLE_URL',
            field=models.URLField(default='https://console.custom.mt/', max_length=256),
        ),
    ]
