# Generated by Django 3.1 on 2025-01-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20241002_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='quote_cc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
