# Generated by Django 3.1 on 2025-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_mainsettings_quote_cc_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='glossaries_url',
            field=models.URLField(default='http://16.171.1.82:8000/', max_length=256),
        ),
    ]
