# Generated by Django 3.1 on 2025-10-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_mainsettings_glossaries_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsettings',
            name='CLOUDSTORAGE_API_URL',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='api_key',
        ),
    ]
