# Generated by Django 3.1 on 2025-10-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20251022_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsettings',
            name='algorithm',
        ),
    ]
