# Generated by Django 3.1 on 2025-10-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_algorithm_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsettings',
            name='glossaries_url',
        ),
    ]
