# Generated by Django 3.1 on 2025-10-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_custom_mt_console_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsettings',
            name='quote_cc_email',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='support_email',
        ),
    ]
