# Generated by Django 3.1 on 2024-09-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('french_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='french_name')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='domains.domaingroup'),
        ),
    ]
