# Generated by Django 3.1 on 2024-11-11 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTranslation',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('name', models.CharField(help_text='Default domain which user will see if domain translation is not configured', max_length=255)),
                ('french_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Activate Default Template option in to the CMT Console for translation to all languages')),
            ],
            options={
                'verbose_name': 'Default Translation',
                'verbose_name_plural': 'Default Translation',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
