# Generated by Django 3.1 on 2025-02-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_defaulttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
