# Generated by Django 3.1 on 2025-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_domain_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaingroup',
            name='icon',
            field=models.CharField(blank=True, default='book-open-text', help_text="Nom de l'icône Phosphor (ex: house, user, gear, file-text, etc.)", max_length=100, null=True, verbose_name='icon'),
        ),
    ]
