# Generated by Django 3.1 on 2025-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_domaingroup_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaingroup',
            name='icon_weight',
            field=models.CharField(choices=[('thin', 'Thin'), ('light', 'Light'), ('regular', 'Regular'), ('bold', 'Bold'), ('fill', 'Fill'), ('duotone', 'Duotone')], default='regular', help_text="Poids de l'icône Phosphor", max_length=20, verbose_name='icon_weight'),
        ),
        migrations.AlterField(
            model_name='domaingroup',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône Phosphor (https://phosphoricons.com/)", max_length=100, null=True, verbose_name='icon'),
        ),
    ]
