# Generated by Django 3.1 on 2025-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='entities',
            field=models.ManyToManyField(blank=True, help_text='Entités associées à ce domaine', related_name='domains', to='domains.Entity', verbose_name='entities'),
        ),
    ]
