# Generated by Django 3.1 on 2025-07-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_domain_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='entities',
            field=models.ManyToManyField(blank=True, help_text='Entities associated with this domain', related_name='domains', to='domains.Entity', verbose_name='entities'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='icon',
            field=models.CharField(blank=True, help_text='Phosphor icon name (https://phosphoricons.com/)', max_length=100, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='icon_weight',
            field=models.CharField(choices=[('thin', 'Thin'), ('light', 'Light'), ('regular', 'Regular'), ('bold', 'Bold'), ('fill', 'Fill'), ('duotone', 'Duotone')], default='regular', help_text='Phosphor icon weight', max_length=10, verbose_name='icon_weight'),
        ),
        migrations.AlterField(
            model_name='domaingroup',
            name='icon',
            field=models.CharField(blank=True, help_text='Phosphor icon name (https://phosphoricons.com/)', max_length=100, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='domaingroup',
            name='icon_weight',
            field=models.CharField(choices=[('thin', 'Thin'), ('light', 'Light'), ('regular', 'Regular'), ('bold', 'Bold'), ('fill', 'Fill'), ('duotone', 'Duotone')], default='regular', help_text='Phosphor icon weight', max_length=10, verbose_name='icon_weight'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='png_file',
            field=models.ImageField(help_text='Entity PNG file', upload_to='entities/', verbose_name='PNG file'),
        ),
    ]
