# Generated by Django 3.1 on 2025-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0010_update_domain_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaingroup',
            name='icon_weight',
        ),
    ]
