# Generated by Django 3.1 on 2025-10-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0011_remove_domaingroup_icon_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='icon_weight',
        ),
    ]
