# Generated by Django 3.1 on 2024-12-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_words_count', models.IntegerField(default=0)),
                ('price_type', models.CharField(choices=[('PER_USER_PER_MONTH', 'Per-user per month (PUMP)'), ('AS_USE', 'As use (AU)')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('access_to_writing', models.BooleanField(default=False, verbose_name='Access to Writing')),
                ('access_to_official_glossaries', models.BooleanField(default=False, verbose_name='Access to Official Glossaries')),
                ('custom_glossaries_count', models.IntegerField(default=0, verbose_name='Custom Glossaries Count')),
                ('access_to_sso', models.BooleanField(default=False, verbose_name='Possible access by SSO authentication logic')),
            ],
        ),
    ]
