# Generated by Django 3.1 on 2024-12-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usergroup_subscription'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_words_count', models.IntegerField(default=0)),
                ('access_to_writing', models.BooleanField(default=False, verbose_name='Access to Writing')),
                ('access_to_official_glossaries', models.BooleanField(default=False, verbose_name='Access to Official Glossaries')),
                ('custom_glossaries_count', models.IntegerField(default=0, verbose_name='Custom Glossaries Count')),
                ('access_to_sso', models.BooleanField(default=False, verbose_name='Possible access by SSO authentication logic')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usergroup')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptiontype')),
            ],
        ),
    ]
