# Generated by Django 3.1 on 2024-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='max_files_count',
            field=models.IntegerField(default=0),
        ),
    ]
