# Generated by Django 3.1 on 2024-12-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usergroup_subscription'),
        ('subscriptions', '0002_subscriptiontype_max_files_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=255)),
                ('max_files_count', models.IntegerField(default=0)),
                ('max_words_count', models.IntegerField(default=0)),
                ('custom_glossaries_count', models.IntegerField(default=0, verbose_name='Custom Glossaries Count')),
                ('translated_words_count', models.IntegerField(default=0)),
                ('translated_files_count', models.IntegerField(default=0)),
                ('access_to_writing', models.BooleanField(default=False, verbose_name='Access to Writing')),
                ('access_to_official_glossaries', models.BooleanField(default=False, verbose_name='Access to Official Glossaries')),
                ('access_to_sso', models.BooleanField(default=False, verbose_name='Possible access by SSO authentication logic')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.usergroup')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='subscriptions.subscriptiontype')),
            ],
        ),
    ]
