# Generated by Django 3.1 on 2025-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_groupsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubscription',
            name='max_symbols_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupsubscription',
            name='translated_symbols_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='max_symbols_count',
            field=models.IntegerField(default=0),
        ),
    ]
