# Generated by Django 3.1 on 2025-06-03 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0004_auto_20250319_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=255)),
                ('max_symbols_count', models.IntegerField(default=0)),
                ('max_files_count', models.IntegerField(default=0)),
                ('max_words_count', models.IntegerField(default=0)),
                ('custom_glossaries_count', models.IntegerField(default=0, verbose_name='Custom Glossaries Count')),
                ('translated_symbols_count', models.IntegerField(default=0)),
                ('translated_words_count', models.IntegerField(default=0)),
                ('translated_files_count', models.IntegerField(default=0)),
                ('access_to_writing', models.BooleanField(default=False, verbose_name='Access to Writing')),
                ('access_to_official_glossaries', models.BooleanField(default=False, verbose_name='Access to Official Glossaries')),
                ('access_to_sso', models.BooleanField(default=False, verbose_name='Possible access by SSO authentication logic')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='price_type',
        ),
        migrations.DeleteModel(
            name='GroupSubscription',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='subscriptions.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
