# Generated by Django 3.1 on 2025-06-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20250603_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='price_type',
        ),
    ]
