# Generated by Django 3.1 on 2025-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20250603_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Stripe Product ID'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='max_symbols_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='max_symbols_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('UNPAID', 'Unpaid'), ('INCOMPLETE_EXPIRED', 'Incomplete Expired'), ('TERMINATED', 'Terminated'), ('UNKNOWN', 'Unknown')], max_length=255),
        ),
    ]
