# Generated by Django 3.1 on 2025-06-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0007_auto_20250624_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(default=434343434, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.user'),
            preserve_default=False,
        ),
    ]
