# Generated by Django 3.1 on 2025-07-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20250624_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('translated_symbols_count', models.IntegerField()),
                ('translated_words_count', models.IntegerField()),
                ('translated_files_count', models.IntegerField()),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_histories', to='subscriptions.subscriptiontype')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_histories', to='subscriptions.usersubscription')),
            ],
        ),
    ]
