# Generated by Django 3.1 on 2025-10-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_counthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='custom_glossaries_count',
            field=models.IntegerField(default=-1, help_text='Nombre maximum de glossaires personnalisés. Utilisez -1 pour illimité (∞).', verbose_name='Custom Glossaries Count'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='max_files_count',
            field=models.IntegerField(default=-1, help_text='Nombre maximum de fichiers. Utilisez -1 pour illimité (∞).'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='max_symbols_count',
            field=models.IntegerField(default=-1, help_text='Nombre maximum de symboles. Utilisez -1 pour illimité (∞).'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='max_words_count',
            field=models.IntegerField(default=-1, help_text='Nombre maximum de mots. Utilisez -1 pour illimité (∞).'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price_type',
            field=models.CharField(choices=[('LEXA', 'Portail lexa'), ('WORD_ADD_IN', 'Microsoft word add-in'), ('API', 'Application Programming Interface')], max_length=255, verbose_name='Product Type'),
        ),
    ]
