# Generated by Django 3.1 on 2025-10-27 10:59

from django.db import migrations


def copy_price_type_to_product_type(apps, schema_editor):
    """
    Copy data from price_type to product_type field
    """
    SubscriptionType = apps.get_model('subscriptions', 'SubscriptionType')
    
    # Copy data from price_type to product_type for all existing records
    for subscription in SubscriptionType.objects.all():
        if hasattr(subscription, 'price_type') and subscription.price_type:
            subscription.product_type = subscription.price_type
            subscription.save()


def reverse_copy_product_type_to_price_type(apps, schema_editor):
    """
    Reverse migration: copy data from product_type back to price_type
    """
    SubscriptionType = apps.get_model('subscriptions', 'SubscriptionType')
    
    # Copy data from product_type back to price_type
    for subscription in SubscriptionType.objects.all():
        if hasattr(subscription, 'product_type') and subscription.product_type:
            subscription.price_type = subscription.product_type
            subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_add_price_type_field'),
    ]

    operations = [
        # First copy data from price_type to product_type
        migrations.RunPython(
            copy_price_type_to_product_type,
            reverse_copy_product_type_to_price_type,
        ),
        
        # Then remove the old price_type field
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='price_type',
        ),
    ]
