# Generated by Django 3.1 on 2025-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_migrate_to_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for this subscription. If not provided, will be automatically generated', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='custom_glossaries_count',
            field=models.IntegerField(default=-1, help_text='Maximum number of custom glossaries. Use -1 for unlimited (∞).', verbose_name='Custom Glossaries Count'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='max_files_count',
            field=models.IntegerField(default=-1, help_text='Maximum number of files. Use -1 for unlimited (∞).'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='max_symbols_count',
            field=models.IntegerField(default=-1, help_text='Maximum number of symbols. Use -1 for unlimited (∞).'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='max_words_count',
            field=models.IntegerField(default=-1, help_text='Maximum number of words. Use -1 for unlimited (∞).'),
        ),
    ]
