# Generated by Django 3.1 on 2025-10-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_fix_price_type_compatibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='price_type',
        ),
    ]
