# Generated by Django 3.1 on 2025-11-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_terminate_expired_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountMetered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reported', models.DateField(blank=True, null=True, verbose_name='Reported Date')),
                ('stripe_usage_record_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Usage Record ID')),
                ('daily_translated_symbols_count', models.IntegerField(default=0)),
                ('daily_translated_words_count', models.IntegerField(default=0)),
                ('daily_translated_files_count', models.IntegerField(default=0)),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_metered', to='subscriptions.usersubscription')),
            ],
        ),
        migrations.AddConstraint(
            model_name='countmetered',
            constraint=models.UniqueConstraint(fields=('user_subscription', 'date'), name='unique_metered_usage_per_day'),
        ),
    ]
