# Generated by Django 3.1 on 2025-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20251124_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, help_text="Identifiant Stripe de l'item metered associé", max_length=64, null=True, verbose_name='Stripe Subscription Item ID'),
        ),
    ]
