# Generated by Django 3.1 on 2025-11-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_usersubscription_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='countmetered',
            name='unique_metered_usage_per_day',
        ),
    ]
