# Generated by Django 3.1 on 2025-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_add_price_type_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='product_type',
            field=models.CharField(choices=[('LEXA', 'Portail lexa'), ('WORD_ADD_IN', 'Microsoft word add-in'), ('API', 'Application Programming Interface')], default='LEXA', max_length=255, verbose_name='Product Type'),
        ),
    ]
