# Generated by Django 3.1 on 2025-10-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_subscriptiontype_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='price_type',
        ),
    ]
