# Generated by Django 3.2.25 on 2026-01-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_remove_unique_constraint_countmetered'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='technical_maximum_symbol_removed',
            field=models.BooleanField(default=False, help_text='If True, ignore the technical maximum symbols limit check', verbose_name='Technical Maximum Symbol Removed'),
        ),
    ]
