# Generated by Django 3.2.25 on 2026-01-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_add_technical_maximum_symbol_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='block_after_first_month',
            field=models.BooleanField(default=False, verbose_name='Block After First Month'),
        ),
    ]
