# Generated by Django 3.1 on 2026-01-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_add_interval_to_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='interval',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], help_text='Billing interval for this subscription (day, week, month, or year)', max_length=10, verbose_name='Billing Interval'),
        ),
    ]
