# Generated by Django 3.1 on 2026-01-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_add_cycles_done_to_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='interval',
            field=models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('year', 'Year')], help_text='Billing interval for this subscription (week, month or year)', max_length=10, verbose_name='Billing Interval'),
        ),
    ]
