# Generated by Django for health check user creation

from django.db import migrations
from django.conf import settings
from django.utils.timezone import now
from django.contrib.auth.hashers import make_password
from datetime import timedelta
import secrets


def create_health_check_user(apps, schema_editor):
    """
    Create health check user with subscription if it doesn't exist.
    
    Creates:
    - UserGroup "LEGAL 230" if it doesn't exist
    - User "health-check" with email from HEALTH_CHECK_USER_EMAIL setting
    - UserSubscription with unlimited limits (-1) and ACTIVE status
    """
    User = apps.get_model('users', 'User')
    UserGroup = apps.get_model('users', 'UserGroup')
    SubscriptionType = apps.get_model('subscriptions', 'SubscriptionType')
    UserSubscription = apps.get_model('subscriptions', 'UserSubscription')
    
    # Get email from settings, use default if not configured
    health_check_email = getattr(settings, 'HEALTH_CHECK_USER_EMAIL', None)
    if not health_check_email:
        health_check_email = 'health-check@legal230.local'
        print(f"⚠ HEALTH_CHECK_USER_EMAIL not configured, using default: {health_check_email}")
    
    # Create or get UserGroup "LEGAL 230"
    group, created = UserGroup.objects.get_or_create(
        name='LEGAL 230',
        defaults={
            'quote_monthly_number': 0
        }
    )
    if created:
        print(f"✓ Created UserGroup: LEGAL 230")
    else:
        print(f"✓ UserGroup already exists: LEGAL 230")
    
    # Check if user already exists
    if User.objects.filter(email=health_check_email).exists():
        print(f"✓ Health check user already exists: {health_check_email}")
        return
    
    # Generate a random password
    random_password = secrets.token_urlsafe(32)
    
    # Create health check user
    user = User.objects.create(
        username='health-check',
        email=health_check_email,
        password=make_password(random_password),
        first_name='Health',
        last_name='Check',
        group=group,
        is_active=True,
        is_staff=False,
        is_superuser=False
    )
    
    print(f"✓ Created health check user: {health_check_email}")
    
    # Find a SubscriptionType without Stripe Product ID
    subscription_type = SubscriptionType.objects.filter(
        stripe_product_id__isnull=True
    ).first()
    
    if not subscription_type:
        # If no subscription without stripe_product_id exists, get any
        subscription_type = SubscriptionType.objects.first()
        
        if not subscription_type:
            print("⚠ Warning: No SubscriptionType found. UserSubscription not created.")
            print("  Please create a SubscriptionType first, then run this migration again.")
            return
    
    print(f"✓ Using SubscriptionType: {subscription_type.name}")
    
    # Create UserSubscription with unlimited limits
    start_date = now()
    end_date = start_date + timedelta(days=3650)  # 10 years
    
    user_subscription = UserSubscription.objects.create(
        user=user,
        subscription=subscription_type,
        status='ACTIVE',
        # Set all max values to -1 (unlimited)
        max_symbols_count=-1,
        max_files_count=-1,
        max_words_count=-1,
        custom_glossaries_count=-1,
        # Initialize translated counts
        translated_symbols_count=0,
        translated_words_count=0,
        translated_files_count=0,
        # Copy access rights from subscription type
        access_to_writing=subscription_type.access_to_writing,
        access_to_official_glossaries=subscription_type.access_to_official_glossaries,
        access_to_sso=subscription_type.access_to_sso,
        # Set dates
        start_date=start_date,
        end_date=end_date,
        # Set interval
        interval='year',
        cycles_done=0
    )
    
    print(f"✓ Created UserSubscription for health check user")
    print(f"  - Status: ACTIVE")
    print(f"  - Max symbols: -1 (unlimited)")
    print(f"  - Max files: -1 (unlimited)")
    print(f"  - Max words: -1 (unlimited)")
    print(f"  - Custom glossaries: -1 (unlimited)")
    print(f"  - Valid until: {end_date.strftime('%Y-%m-%d')}")


def reverse_health_check_user(apps, schema_editor):
    """
    Remove health check user and associated data.
    """
    User = apps.get_model('users', 'User')
    
    health_check_email = getattr(settings, 'HEALTH_CHECK_USER_EMAIL', None)
    if not health_check_email:
        health_check_email = 'health-check@legal230.local'
    
    # Delete user (cascade will delete UserSubscription)
    deleted_count, _ = User.objects.filter(email=health_check_email).delete()
    
    if deleted_count > 0:
        print(f"✓ Deleted health check user: {health_check_email}")
    else:
        print(f"✓ Health check user not found: {health_check_email}")


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('users', '__latest__'),
        ('subscriptions', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_health_check_user, reverse_health_check_user),
    ]
