# Generated by Django 3.1 on 2026-01-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_create_health_check_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheckresult',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Health Check Result', 'verbose_name_plural': 'Health Check Results'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckrun',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Health Check Run', 'verbose_name_plural': 'Health Check Runs'},
        ),
        migrations.AlterField(
            model_name='healthcheckresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthcheckrun',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
