# Generated by Django 3.1 on 2026-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20260119_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckresult',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('external_api', 'External API'), ('translation', 'Translation'), ('database', 'Database'), ('docker', 'Docker'), ('document_processing', 'Document Processing')], max_length=50),
        ),
    ]
