"""
WeasyPrint PDF generation health check.

Tests the PDF generation capability using WeasyPrint library.
"""
import logging
from typing import Dict, Any

from ..base import BaseHealthCheck

logger = logging.getLogger(__name__)


class WeasyPrintHealthCheck(BaseHealthCheck):
    """
    Health check for WeasyPrint PDF generation.
    
    Tests:
    - WeasyPrint library import
    - PDF generation from simple HTML
    - Validation of generated PDF bytes
    """
    
    service_name = "WeasyPrint PDF Generation"
    category = "document_processing"
    
    # Test HTML for PDF generation
    TEST_HTML = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Health Check Test</title>
        <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #333; }
        </style>
    </head>
    <body>
        <h1>Health Check Test</h1>
        <p>This is a test PDF generated by WeasyPrint.</p>
    </body>
    </html>
    """
    
    def _check(self):
        """
        Execute WeasyPrint health check.
        
        Returns:
            HealthCheckResult with success status and details
        """
        from ..base import HealthCheckResult
        
        try:
            # Step 1: Import WeasyPrint
            import_result = self._check_weasyprint_import()
            if not import_result['success']:
                return self._create_error_result(
                    message=import_result['error'],
                    details=import_result.get('details')
                )
            
            # Step 2: Generate PDF from HTML
            pdf_result = self._generate_test_pdf()
            if not pdf_result['success']:
                return self._create_error_result(
                    message=pdf_result['error'],
                    details=pdf_result.get('details')
                )
            
            # Step 3: Validate PDF
            validation_result = self._validate_pdf(pdf_result['pdf_bytes'])
            if not validation_result['success']:
                return self._create_error_result(
                    message=validation_result['error'],
                    details=validation_result.get('details')
                )
            
            return self._create_success_result(
                message="WeasyPrint PDF generation is working correctly",
                details={
                    'library': 'weasyprint',
                    'pdf_size_bytes': len(pdf_result['pdf_bytes']),
                    'html_size_bytes': len(self.TEST_HTML),
                    'validation': 'PDF signature valid'
                }
            )
            
        except Exception as e:
            logger.error(f"WeasyPrint health check failed: {str(e)}", exc_info=True)
            return self._create_error_result(
                message=f"Unexpected error: {str(e)}",
                error=e,
                details={'exception_type': type(e).__name__}
            )
    
    def _check_weasyprint_import(self) -> Dict[str, Any]:
        """
        Check if WeasyPrint can be imported.
        
        Returns:
            Dictionary with success status
        """
        try:
            from weasyprint import HTML
            return {
                'success': True,
                'details': {'import': 'success'}
            }
        except ImportError as e:
            return {
                'success': False,
                'error': f"Failed to import WeasyPrint: {str(e)}",
                'details': {'import': 'failed'}
            }
        except Exception as e:
            return {
                'success': False,
                'error': f"Error importing WeasyPrint: {str(e)}",
                'details': {'exception_type': type(e).__name__}
            }
    
    def _generate_test_pdf(self) -> Dict[str, Any]:
        """
        Generate a test PDF from HTML.
        
        Returns:
            Dictionary with success status and PDF bytes
        """
        try:
            from weasyprint import HTML
            
            # Generate PDF
            pdf_bytes = HTML(string=self.TEST_HTML).write_pdf()
            
            if not pdf_bytes:
                return {
                    'success': False,
                    'error': "PDF generation returned empty bytes"
                }
            
            return {
                'success': True,
                'pdf_bytes': pdf_bytes
            }
            
        except Exception as e:
            logger.error(f"Failed to generate test PDF: {str(e)}", exc_info=True)
            return {
                'success': False,
                'error': f"PDF generation failed: {str(e)}",
                'details': {'exception_type': type(e).__name__}
            }
    
    def _validate_pdf(self, pdf_bytes: bytes) -> Dict[str, Any]:
        """
        Validate that the generated bytes are a valid PDF.
        
        Args:
            pdf_bytes: PDF bytes to validate
            
        Returns:
            Dictionary with success status
        """
        try:
            # Check PDF magic number (PDF files start with %PDF-)
            if not pdf_bytes.startswith(b'%PDF-'):
                return {
                    'success': False,
                    'error': "Generated file is not a valid PDF (missing PDF signature)",
                    'details': {'signature': pdf_bytes[:10].hex()}
                }
            
            # Check minimum size (a valid PDF should be at least a few hundred bytes)
            if len(pdf_bytes) < 100:
                return {
                    'success': False,
                    'error': f"Generated PDF is too small ({len(pdf_bytes)} bytes)",
                    'details': {'size_bytes': len(pdf_bytes)}
                }
            
            # Check PDF end marker
            if b'%%EOF' not in pdf_bytes:
                return {
                    'success': False,
                    'error': "Generated PDF is incomplete (missing EOF marker)"
                }
            
            return {
                'success': True,
                'details': {
                    'signature': 'valid',
                    'size_bytes': len(pdf_bytes),
                    'eof_marker': 'present'
                }
            }
            
        except Exception as e:
            return {
                'success': False,
                'error': f"PDF validation failed: {str(e)}",
                'details': {'exception_type': type(e).__name__}
            }
